image: Visual Studio 2017

before_deploy:
  - msbuild /p:Configuration=Release /p:DebugSymbols=false /p:DebugType=None
  - cd bin/Release
  - 7z a full.7z *
  - 7z a mini.7z *.exe *.wav
  - appveyor PushArtifact full.7z
  - appveyor PushArtifact mini.7z

deploy:
  artifact: /.*\.7z/
  auth_token:
    secure: J1DFsRUBaJKZ2HqHKOQEA427FUsKo6rDTxtxyUwARP7k0Ac5SgX1qn77+LYXdwk6
  description: ''
  on:
    appveyor_repo_tag: true
  provider: GitHub

branches:
  only:
    - latest

build: false